config/routes.rb
Chaturly::Application.routes.draw do
  root 'home#index'

  resources :sections, only: [:show], :path => 'c' do
    resources :messages, only: [:index, :create]
    resources :analytics, only: [:index]
  end

  match 'search/feedback' => 'search#feedback', via: :get

  resources :search, only: [:index]

  resources :about, only: [:index]
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :section

  validates :content, presence: true
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :messages

  def to_param
    title # or whatever you set :url_attribute to
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  before_action :set_title, :set_section
  def index
  end

  private
    def set_title
      @title = params[:section_id]
    end

    def set_section
      @section = Section.find_by_title(@title)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_section_title, :set_section

  def index
    @messages = @section.messages

    render json: @messages

    # respond_to do |format|
    #   format.json { results json: @messages }
    # end
  end

  def create
    # create message
    @message = @section.messages.build(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @section }

        cookies[:username] = @message.username
      else
        format.html { redirect_to @section, flash: { error: 'Unable to create message.' } }
      end
    end
  end

  private
    def set_section_title
      @section_title = params[:section_id]
    end

    def set_section
      @section = Section.find_by_title(@section_title)

      puts 'Section'
      puts @section
    end

    def message_params
      params.require(:message).permit(:content, :username)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :set_url, :set_message_details

  def index
    if valid?(@url) || valid?('http://' + @url)
      # remove unwanted parts and symbols
      encoded_query = @url.sub(/^https?\:\/\//, '').sub(/^www./, '').gsub(/\//, ' ').gsub(/\./, ' ').to_url

      redirect_to section_path(encoded_query, :url => @url)
    else
      redirect_to root_path, flash: { :error => @url + ' is not a valid URL' }
    end
  end

  def feedback
    puts 'feedback'
    if valid?(@url) || valid?('http://' + @url)
      puts 'valid'
      # remove unwanted parts and symbols
      encoded_query = @url.sub(/^https?\:\/\//, '').sub(/^www./, '').gsub(/\//, ' ').gsub(/\./, ' ').to_url

      puts 'encoded'

      redirect_to section_path(encoded_query, {:url => @url, :username => @username, :content => @content, :vote => @vote})
    end
  end

  private
    def set_url
      @url = params[:url]
    end

    def set_message_details
      @username = params[:username]
      @content = params[:content]
      @vote = params[:vote]
    end

    def valid?(url)
      uri = URI.parse(url)
      uri.kind_of?(URI::HTTP)
    rescue URI::InvalidURIError
      false
    end

    def message?
      !@username.nil? && !@content.nil?
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_title, :set_section, :set_message_details

  def show
    @message = Message.new

    if !@username.nil? && !@message.nil? && !@vote.nil?
      puts 'add message'

      message = Message.new
      message.section = @section
      message.username = @username
      message.content = @content

      if message.save
        render nothing: true
      end
    end
  end

  private
    def set_title
      @title = params[:id]
    end

    def set_section
      if @title.blank?
        redirect_to root_path
      else
        @section = Section.find_by_title(@title)

        # create section if does not exist
        if @section.nil? 
          url = params[:url]

          if url.blank?
            redirect_to root_path
          else
            @section = Section.new
            @section.title = @title
            @section.url = url
            @section.save

            params.delete :url
          end
        end
      end
    end

    def set_message_details
      @username = params[:username]
      @content = params[:content]
      @vote = params[:vote]
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/about/index.html.erb
<div class="index inner-container">
  <div class="pure-g-r">
    <div class="pure-u-1">
      <h1>
        <%= link_to 'chaturly', root_path %> / about
      </h1>

      <p>
        We're a young start-up with big ambitions! Every website on the internet now has a Chaturly chat site – and it's FREE for users! If you have a website or blog then go to our home page now and enter your homepage URL to view your brand new chat site. If you like it then copy the HTML snippet below and paste it into your website! If you have any difficulty then we'd be pleased to try and help.
      </p>

      <textarea>
        <a class="bookmarklet" href="javascript:(function()%7Bfunction%20callback()%7B(function(%24)%7Bvar%20jQuery%3D%24%3Bvar%20metas%20%3D%20document.getElementsByTagName('meta')%3Bvar%20tags%20%3D%20%5B%5D%3Bfor%20(i%20%3D%200%3B%20i%20%3C%20metas.length%3B%20i%2B%2B)%20%7Bvar%20tf%20%3D%20false%3Bif%20(metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'og%3Atitle'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'description'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'content-language'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'country'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'og%3Asite_name')%20%7Bif%20(metas%5Bi%5D.getAttribute(%22content%22)!%3Dnull)%20%7Btags.push(%7B%20Key%3A%20metas%5Bi%5D.getAttribute(%22property%22)%2C%20value%3A%20metas%5Bi%5D.getAttribute(%22content%22)%20%7D)%3B%7D%7D%7Dwindow.location%3D'http%3A%2F%2Fwww.chaturly.com%2Fsearch%3Furl%3D'%20%2B%20encodeURIComponent(window.location.href)%20%2B%20'%26Meta%3D'%20%2B%20encodeURIComponent(JSON.stringify(tags))%7D)(jQuery.noConflict(true))%7Dvar%20s%3Ddocument.createElement(%22script%22)%3Bs.src%3D%22https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%22%3Bif(s.addEventListener)%7Bs.addEventListener(%22load%22%2Ccallback%2Cfalse)%7Delse%20if(s.readyState)%7Bs.onreadystatechange%3Dcallback%7Ddocument.body.appendChild(s)%3B%7D)()"><img src="http://s23.postimg.org/eaazx3lnr/Chaturly2.png" /></a>
      </textarea>
    </div>
  </div>

  <div class="pure-g-r feedback">
    <div class="pure-u-1">
      <a class="bookmarklet" href="javascript:(function()%7Bfunction%20callback()%7B(function(%24)%7Bvar%20jQuery%3D%24%3Bvar%20metas%20%3D%20document.getElementsByTagName('meta')%3Bvar%20tags%20%3D%20%5B%5D%3Bfor%20(i%20%3D%200%3B%20i%20%3C%20metas.length%3B%20i%2B%2B)%20%7Bvar%20tf%20%3D%20false%3Bif%20(metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'og%3Atitle'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'description'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'content-language'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'country'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'og%3Asite_name')%20%7Bif%20(metas%5Bi%5D.getAttribute(%22content%22)!%3Dnull)%20%7Btags.push(%7B%20Key%3A%20metas%5Bi%5D.getAttribute(%22property%22)%2C%20value%3A%20metas%5Bi%5D.getAttribute(%22content%22)%20%7D)%3B%7D%7D%7Dwindow.location%3D'http%3A%2F%2Fwww.chaturly.com%2Fsearch%3Furl%3D'%20%2B%20encodeURIComponent(window.location.href)%20%2B%20'%26Meta%3D'%20%2B%20encodeURIComponent(JSON.stringify(tags))%7D)(jQuery.noConflict(true))%7Dvar%20s%3Ddocument.createElement(%22script%22)%3Bs.src%3D%22https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%22%3Bif(s.addEventListener)%7Bs.addEventListener(%22load%22%2Ccallback%2Cfalse)%7Delse%20if(s.readyState)%7Bs.onreadystatechange%3Dcallback%7Ddocument.body.appendChild(s)%3B%7D)()"><img src="http://s23.postimg.org/eaazx3lnr/Chaturly2.png" /></a>
    </div>
  </div>
  
</div>

app/views/analytics/index.html.erb
<div class="index inner-container">
  <div class="pure-g-r header">
    <div class="pure-u-1">
      <h1>
        <%= link_to 'chaturly', root_path %> / <%= link_to @section.title, section_path(@section) %> / analytics
      </h1>
    </div>
  </div>

  <div class="pure-g-r chart">
    <div class="pure-u-1">
      <div id="Chart3" style="height: 400px; min-width: 400px"></div>
    </div>
  </div>

  <div class="pure-g-r chart">
    <div class="pure-u-1">
      <div id="Chart2" style="height: 400px; min-width: 400px"></div>
    </div>
  </div>

  <div class="pure-g-r chart">
    <div class="pure-u-1">
      <div id="Chart1" style="height: 400px; min-width: 400px"></div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="index">
  <div class="pure-g-r hero">
    <div class="pure-u-1">
      <div class="pure-g-r">
        <div class="pure-u-1">
          <%= image_tag('logo-100.png') %>

          <h1>Chaturly</h1>
        </div>
      </div>

      <div class="pure-g-r">
        <div class="pure-u-1">
          <h2>Group chat about any URL, with anyone.</h2>
        </div>
      </div>

      <div class="pure-g-r">
        <div class="pure-u-1">
          <a class="bookmarklet" href="javascript:(function()%7Bfunction%20callback()%7B(function(%24)%7Bvar%20jQuery%3D%24%3Bvar%20metas%20%3D%20document.getElementsByTagName('meta')%3Bvar%20tags%20%3D%20%5B%5D%3Bfor%20(i%20%3D%200%3B%20i%20%3C%20metas.length%3B%20i%2B%2B)%20%7Bvar%20tf%20%3D%20false%3Bif%20(metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'og%3Atitle'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'description'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'content-language'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'country'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'og%3Asite_name')%20%7Bif%20(metas%5Bi%5D.getAttribute(%22content%22)!%3Dnull)%20%7Btags.push(%7B%20Key%3A%20metas%5Bi%5D.getAttribute(%22property%22)%2C%20value%3A%20metas%5Bi%5D.getAttribute(%22content%22)%20%7D)%3B%7D%7D%7Dwindow.location%3D'http%3A%2F%2Fwww.chaturly.com%2Fsearch%3Furl%3D'%20%2B%20encodeURIComponent(window.location.href)%20%2B%20'%26Meta%3D'%20%2B%20encodeURIComponent(JSON.stringify(tags))%7D)(jQuery.noConflict(true))%7Dvar%20s%3Ddocument.createElement(%22script%22)%3Bs.src%3D%22https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%22%3Bif(s.addEventListener)%7Bs.addEventListener(%22load%22%2Ccallback%2Cfalse)%7Delse%20if(s.readyState)%7Bs.onreadystatechange%3Dcallback%7Ddocument.body.appendChild(s)%3B%7D)()"><img src="http://s23.postimg.org/eaazx3lnr/Chaturly2.png" /></a>
        </div>
      </div>
    </div>
  </div>

  <div class="pure-g-r search">
    <div class="pure-u-1">
      <%= render 'search/form' %>
    </div>
  </div>

  <div class="pure-g-r popular">
    <div class="pure-u-1-3">
      <div class="pure-g-r popular-title">
        <div class="pure-u-1">
          <h2>Featured Pages</h2>
        </div>
      </div>

      <div class="pure-g-r popular-items">
        <div class="pure-u-1">
          <div class="pure-g-r">
            <div class="pure-u-1">
              <%= link_to 'Manchester Startup Weekend', '/c/manchester-startupweekend-org' %>
            </div>
          </div>

          <div class="pure-g-r">
            <div class="pure-u-1">
              <%= link_to 'Growot', '/c/growot-com' %>
            </div>
          </div>

          <div class="pure-g-r">
            <div class="pure-u-1">
              <%= link_to 'Drew Forsyth', '/c/drewforsyth-com' %>
            </div>
          </div>

          <div class="pure-g-r">
            <div class="pure-u-1">
              <%= link_to 'Lightning Slap', '/c/lightningslap-co' %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="pure-u-1-3">
      <h2>
        <%= link_to 'About', about_index_path %>
      </h2>
    </div>

    <div class="pure-u-1-3">
      <div class="pure-g-r popular-title">
        <div class="pure-u-1">
          <h2>Bookmarklet</h2>
        </div>
      </div>

      <div class="pure-g-r feedback-control">
        <div class="pure-u-1">
          <a class="bookmarklet" href="javascript:(function()%7Bfunction%20callback()%7B(function(%24)%7Bvar%20jQuery%3D%24%3Bvar%20metas%20%3D%20document.getElementsByTagName('meta')%3Bvar%20tags%20%3D%20%5B%5D%3Bfor%20(i%20%3D%200%3B%20i%20%3C%20metas.length%3B%20i%2B%2B)%20%7Bvar%20tf%20%3D%20false%3Bif%20(metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'og%3Atitle'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'description'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'content-language'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'country'%7C%7C%20metas%5Bi%5D.getAttribute(%22property%22)%20%3D%3D%20'og%3Asite_name')%20%7Bif%20(metas%5Bi%5D.getAttribute(%22content%22)!%3Dnull)%20%7Btags.push(%7B%20Key%3A%20metas%5Bi%5D.getAttribute(%22property%22)%2C%20value%3A%20metas%5Bi%5D.getAttribute(%22content%22)%20%7D)%3B%7D%7D%7Dwindow.location%3D'http%3A%2F%2Fwww.chaturly.com%2Fsearch%3Furl%3D'%20%2B%20encodeURIComponent(window.location.href)%20%2B%20'%26Meta%3D'%20%2B%20encodeURIComponent(JSON.stringify(tags))%7D)(jQuery.noConflict(true))%7Dvar%20s%3Ddocument.createElement(%22script%22)%3Bs.src%3D%22https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js%22%3Bif(s.addEventListener)%7Bs.addEventListener(%22load%22%2Ccallback%2Cfalse)%7Delse%20if(s.readyState)%7Bs.onreadystatechange%3Dcallback%7Ddocument.body.appendChild(s)%3B%7D)()">Chaturly</a>      
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="<%= controller.controller_name %>">
<head>
  <title>Chaturly</title>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="http://code.highcharts.com/stock/highstock.js"></script>
  <script src="http://code.highcharts.com/stock/modules/exporting.js"></script>
  <script src="http://code.highcharts.com/highcharts-more.js"></script>
  <meta name="viewport" content="initial-scale=1">
</head>
<body>
  <%= yield %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-45979942-1', 'chaturly.com');
    ga('send', 'pageview');

  </script>
</body>
</html>

app/views/messages/_form.html.erb
<div class="pure-g-r">
  <div class="pure-u-1">
    <%= form_for [@section, @message], method: 'post', class: 'pure-form' do |f| %>
      <div class="pure-g-r">
        <div class="pure-u-1-5 content">
          <%= f.text_field :username, :value => cookies[:username], placeholder: 'Name (optional)...' %>
        </div>

        <div class="pure-u-3-5 content">
          <%= f.text_field :content, placeholder: 'Write a message...', autofocus: true %>
        </div>

        <div class="pure-u-1-5 content">
          <%= f.submit 'Submit', class: 'pure-button pure-button-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/search/_form.html.erb
<div class="pure-g-r">
  <div class="pure-u-1">
    <%= form_tag search_index_path, method: 'get' , class: 'pure-form' do %>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, :class => "flash #{key}") %>
      <% end %>
      
      <%= text_field_tag :url, nil, placeholder: 'Enter a URL...', autofocus: true %>

      <%= submit_tag 'Submit', name: nil, class: 'pure-button' %>
    <% end %>
  </div>
</div>

app/views/search/search.html.erb
<h1>Search#search</h1>
<p>Find me in app/views/search/search.html.erb</p>

app/views/sections/show.html.erb
<div class="show inner-container">
  <div class="pure-g-r header">
    <div class="pure-u-1">
      <a class="section-logo" href="/">
        <%= image_tag('logo.png') %>
      </a>
      
      <div class="header-details">
        <%= link_to 'chaturly', root_path %> / <%= link_to @section.title, @section.url, target: '_blank' %>
      </div>

      <a class="analytics-link" href='<%= section_analytics_path(@section) %>'>
        <img src="<%= image_path('analytics.png') %>" />
      </a>
    </div>
  </div>

  <div class="pure-g-r main">
    <div class="pure-u-1 main-inner">
      <% if @section.nil? || @section.messages.empty? %>
        <div class="empty">
          Be the first to chat!
        </div>
      <% else %>
        <% @section.messages.order('created_at ASC').each do |message| %>
          <div class="pure-g-r message">
            <div class="pure-u-1">
              <div class="avatar">
                <img src="http://www.gravatar.com/avatar/<%= Random.rand(100) %>?s=32&amp;d=identicon&amp;r=PG" alt="">
              </div>

              <div class="body">
                <div class="text">
                  <%= message.content %>
                </div>

                <div class="details">
                  <div class="pure-g-r">
                    <div class="pure-u-1-2">
                      posted by <%= !message.username.blank? ? message.username : 'Anonymous' %>
                    </div>

                    <div class="pure-u-1-2 right">
                      <%= time_ago_in_words(message.created_at) %> ago
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="pure-g-r interface">
    <div class="pure-u-1">
      <%= render 'messages/form' %>
    </div>
  </div>
</div>